# Generated by Django 3.0.3 on 2020-06-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMP', '0004_remove_student_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='mentor_regn',
            field=models.IntegerField(default=0),
        ),
    ]
