# Generated by Django 3.0.3 on 2020-06-02 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SMP', '0006_auto_20200601_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='name',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='pasw',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='usname',
        ),
        migrations.AddField(
            model_name='mentor',
            name='contactn',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='mentor',
            name='hostel',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='mentor',
            name='mentor',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='SMP.Student'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='roomn',
            field=models.CharField(default='', max_length=7),
        ),
    ]
