# Generated by Django 3.0.3 on 2020-06-02 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SMP', '0007_auto_20200602_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='myear',
        ),
    ]
