# Generated by Django 3.0.7 on 2020-08-01 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalMentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regn', models.CharField(max_length=16)),
                ('dept', models.CharField(max_length=40)),
                ('roomn', models.CharField(default='', max_length=7)),
                ('hostel', models.CharField(default='', max_length=40)),
                ('contactn', models.CharField(default='', max_length=15)),
                ('name', models.CharField(default='', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='UserA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Alumni_index', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentor_name', models.CharField(max_length=30)),
                ('mentor_regn', models.CharField(default='', max_length=10)),
                ('branch', models.CharField(max_length=40)),
                ('syear', models.CharField(default='', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SMP.UserA')),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomn', models.CharField(default='', max_length=7)),
                ('hostel', models.CharField(default='', max_length=40)),
                ('contactn', models.CharField(default='', max_length=15)),
                ('mentor', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='SMP.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='')),
                ('alumniA', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SMP.UserA')),
            ],
        ),
    ]
