# Generated by Django 3.0.3 on 2020-05-26 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='myear',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='syear',
            field=models.CharField(default='', max_length=10),
        ),
    ]
