# Generated by Django 3.0.3 on 2020-05-31 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SMP', '0003_student_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='img',
        ),
    ]
