# Generated by Django 3.0.3 on 2020-06-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMP', '0005_student_mentor_regn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mentor_regn',
            field=models.CharField(default='', max_length=10),
        ),
    ]
