# Generated by Django 3.0.3 on 2020-06-04 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMP', '0008_auto_20200602_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalMentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regn', models.CharField(max_length=16)),
                ('dept', models.CharField(max_length=40)),
                ('roomn', models.CharField(default='', max_length=7)),
                ('hostel', models.CharField(default='', max_length=40)),
                ('contactn', models.CharField(default='', max_length=15)),
            ],
        ),
    ]
