# Generated by Django 3.0.3 on 2020-06-04 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMP', '0009_finalmentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalmentor',
            name='name',
            field=models.CharField(default='', max_length=40),
        ),
    ]
