# Generated by Django 3.0.7 on 2020-08-01 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SMP', '0010_finalmentor_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumni_index', models.BooleanField(default=False)),
                ('userA', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('field', models.CharField(max_length=50)),
                ('alumni', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SMP.UserA')),
            ],
        ),
    ]
